#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Smoovies.Resource", IsApplication=true)]

namespace Smoovies
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000b
			public const int btnFav = 2131034123;
			
			// aapt resource value: 0x7f05000a
			public const int btnPlay = 2131034122;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int ivBG = 2131034114;
			
			// aapt resource value: 0x7f050017
			public const int ivMovie = 2131034135;
			
			// aapt resource value: 0x7f050004
			public const int ivPoster = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout1 = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int linearLayout2 = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int linearLayout3 = 2131034117;
			
			// aapt resource value: 0x7f050014
			public const int listFav = 2131034132;
			
			// aapt resource value: 0x7f050013
			public const int listNowPlaying = 2131034131;
			
			// aapt resource value: 0x7f050012
			public const int listPopular = 2131034130;
			
			// aapt resource value: 0x7f05000f
			public const int listSimilar = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int listTopRated = 2131034128;
			
			// aapt resource value: 0x7f05000d
			public const int llSimilar = 2131034125;
			
			// aapt resource value: 0x7f050016
			public const int llTile = 2131034134;
			
			// aapt resource value: 0x7f050015
			public const int progBar = 2131034133;
			
			// aapt resource value: 0x7f050008
			public const int ratingScore = 2131034120;
			
			// aapt resource value: 0x7f050011
			public const int tv = 2131034129;
			
			// aapt resource value: 0x7f05000c
			public const int tvDescr = 2131034124;
			
			// aapt resource value: 0x7f050007
			public const int tvReleaseDate = 2131034119;
			
			// aapt resource value: 0x7f05000e
			public const int tvSimilar = 2131034126;
			
			// aapt resource value: 0x7f050006
			public const int tvTitle = 2131034118;
			
			// aapt resource value: 0x7f050009
			public const int tvVotes = 2131034121;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ActivityDetail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ActivityHome = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ActivitySplash = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MovieTile = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] RecyclerView = new int[] {
					16842948,
					16842993,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 1
			public const int RecyclerView_android_descendantFocusability = 1;
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 2
			public const int RecyclerView_layoutManager = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_reverseLayout = 4;
			
			// aapt resource value: 3
			public const int RecyclerView_spanCount = 3;
			
			// aapt resource value: 5
			public const int RecyclerView_stackFromEnd = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
